# Generated by Django 3.2.4 on 2023-03-27 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Whisper',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model', models.CharField(choices=[('tiny.en', 'tiny.en'), ('tiny', 'tiny'), ('base.en', 'base.en'), ('base', 'base'), ('small.en', 'small.en'), (' ', 'small'), ('medium.en', 'medium.en'), ('medium', 'medium'), ('large-v1', 'large-v1'), ('large-v2', 'large-v2'), ('large', 'large')], max_length=10)),
                ('output_format', models.CharField(choices=[('', 'all'), ('Text', 'txt'), ('Vtt', 'vtt'), ('Srt', 'srt'), ('Tsv', 'tsv'), ('Json', 'json')], max_length=5)),
                ('task', models.CharField(choices=[('', 'transcribe'), ('Translate', 'translate')], max_length=10)),
                ('language', models.CharField(max_length=50)),
            ],
        ),
    ]
