# Generated by Django 3.2.4 on 2023-03-29 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whisper', '0002_alter_whisper_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='whisper',
            name='name',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
    ]
