# Generated by Django 3.2.4 on 2023-04-03 14:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('whisper', '0004_alter_whisper_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='whisper',
            name='upload_file',
            field=models.FileField(default='images/MPI_logo_regular.png', upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='whisper',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='whisper',
            name='output_format',
            field=models.CharField(choices=[('all', 'all'), ('Text', 'txt'), ('Vtt', 'vtt'), ('Srt', 'srt'), ('Tsv', 'tsv'), ('Json', 'json')], max_length=5),
        ),
    ]
