# Generated by Django 4.2.8 on 2024-07-01 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whisper', '0007_whisper_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whisper',
            name='upload_file',
            field=models.FilePathField(blank=True, help_text='This is a file list to which the Django server has access.', max_length=500, path='/mnt/c/pavsri/Downloads', recursive=True),
        ),
    ]
