# Generated by Django 4.2.8 on 2024-07-01 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whisper', '0008_alter_whisper_upload_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whisper',
            name='upload_file',
            field=models.CharField(max_length=255),
        ),
    ]
