# Generated by Django 4.2.8 on 2024-07-05 11:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('whisper', '0009_alter_whisper_upload_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whisper',
            name='path',
        ),
        migrations.RemoveField(
            model_name='whisper',
            name='upload_file',
        ),
        migrations.AddField(
            model_name='whisper',
            name='input_file_path',
            field=models.CharField(default=django.utils.timezone.now, max_length=10000),
            preserve_default=False,
        ),
    ]
